### ISSUE TITLE
Build failure!

### ISSUE THREAD

**Issue by preston** [c-schuler/Cql_Engine#1]
Straight clone from master HEAD fails as follows...

    $ gradle build
    :cql-engine:generateSources UP-TO-DATE
    :cql-engine:compileJava UP-TO-DATE
    :cql-engine:processResources NO-SOURCE
    :cql-engine:classes UP-TO-DATE
    :cql-engine:jar UP-TO-DATE
    :cql-engine:assemble UP-TO-DATE
    :cql-engine:compileTestJava
    /Users/preston/Developer/git/Cql_Engine/Src/java/cql-engine/src/test/java/org/cqframework/cql/execution/CqlExecutionTestBase.java:35: error: constructor LibraryManager in class LibraryManager cannot be applied to given types;
                LibraryManager libraryManager = new LibraryManager();
                                                ^
      required: ModelManager
      found: no arguments
      reason: actual and formal argument lists differ in length
    /Users/preston/Developer/git/Cql_Engine/Src/java/cql-engine/src/test/java/org/cqframework/cql/execution/CqlExecutionTestBase.java:41: error: no suitable method found for fromFile(File,LibraryManager,Options[])
                    CqlTranslator translator = CqlTranslator.fromFile(cqlFile, libraryManager, options.toArray(new CqlTranslator.Options[options.size()]));
                                                            ^
        method CqlTranslator.fromFile(String,ModelManager,LibraryManager,Options...) is not applicable
          (argument mismatch; File cannot be converted to String)
        method CqlTranslator.fromFile(File,ModelManager,LibraryManager,Options...) is not applicable
          (argument mismatch; LibraryManager cannot be converted to ModelManager)
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    2 errors
    :cql-engine:compileTestJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':cql-engine:compileTestJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 2.238 secs

**Comment by c-schuler** [comment]
I am not maintaining this...
For the cql_engine, please use this repo:
https://github.com/DBCG/cql_engine
Thanks

**Comment by preston** [comment]
Yeah I just heard from Bryn. Not sure where I was linked from, though I'd suggest deleting the repo to prevent others from making the same mistake. :)
